" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'kristijanhusak/vim-hybrid-material'

call vundle#end()
filetype plugin indent on

" vim-hybrid-material
syntax enable
set background=dark
colorscheme hybrid_material
set t_Co=256

" 中文编码
set encoding=utf-8
set fenc=utf-8
set fileencodings=ucs-bom,utf-8,cp936

" General Setting
set nu
set nobackup

" Search
set incsearch
set hlsearch

" Statusline
set laststatus=2
set statusline=%F%=
set statusline+=%l,%c
set statusline+=\    
set statusline+=%p%%
hi statusline ctermbg=white ctermfg=234

" 恢复光标位置
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

" 配置立即生效
autocmd! bufwritepost $HOME/.vimrc source %
